title: cetusian
description: Detection and embedded intelligence, AI engineering, and Superbird Labs.
baseurl: ""
url: "https://cetusian.com"
keywords:
  - detection
  - embedded intelligence
  - ai engineering
  - edge ai
  - superbird labs
collections:
  projects:
    output: true
    permalink: /projects/:title/
markdown: kramdown
kramdown:
  syntax_highlighter: rogue
# Force rebuild
