# Site settings
title: cetusian
description: Detection and embedded intelligence, AI engineering, and Superbird Labs.
url: "https://cetusian.com"
baseurl: ""
keywords:
  - detection
  - embedded intelligence
  - ai engineering
  - edge ai
  - superbird labs

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
